format = """
$username\
$hostname\
$directory\
$status\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$java\
$python\
$lua\
$php\
$c\
$golang\
$rust\
$ruby\
$package\
$cmd_duration $jobs\
$line_break\
$character"""

[username]
show_always = true
format = '[$user](bold purple) '

[status]
# '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
format = '$symbol'
symbol = '[●\($status\)](bright-red) '
success_symbol = '[●](green) '
not_executable_symbol = '[⌽\($status\)](bright-red) '
not_found_symbol = '[◎\($status\)](bright-red) '
sigint_symbol = '[✶\($status\)](bright-red) '
signal_symbol = '[✕\($status\)](bright-red) '
recognize_signal_code = true
map_symbol = true
disabled = false

[nodejs]
symbol = "󰎙 "
format = "[$symbol($version )]($style)"

[java]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold orange"

[python]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold blue"

[lua]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold cyan"

[php]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold magenta"

[c]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold blue"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold cyan"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold red"

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold red"

[fill]
symbol = " "

[directory]
style = "bold blue"
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[package]
symbol = "󰏗 "
format = "[$symbol]($style)"

[jobs]
symbol = " "
style = "grey"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bright-black'
conflicted = ' '
up_to_date = ' '
untracked = ' '
ahead = '⇡${count}'
behind = '⇣${count}'
stashed = ' '
modified = '襁'
staged = '[++\($count\)](green)'
renamed = ' '
deleted = ' '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "bold yellow"

# [os]
# disabled = false
# [os.symbols]
# Arch = " "
